version: '3.5'

services:
  atl-bitbucket:
    image: atlassian/bitbucket-server:6.10.5
    container_name: atl-bitbucket
    restart: unless-stopped
    env_file: env/bitbucket.env
    depends_on: 
      - atl-bitbucket-db
    volumes:
      - ${BITBUCKET_VOLUME_DATA}:/var/atlassian/application-data/bitbucket
    networks:
      - default
      - db
    ports:
      - ${BITBUCKET_PORT_1}:7990
      - ${BITBUCKET_PORT_2}:7999

  atl-bamboo:
    image: atlassian/bamboo-server:7.2.2
    container_name: atl-bamboo
    restart: unless-stopped
    env_file: env/bamboo.env
    depends_on: 
      - atl-bamboo-db
    volumes:
      - ${BAMBOO_VOLUME_DATA}:/var/atlassian/application-data/bamboo
    networks:
      - default
      - db
    ports:
      - ${BAMBOO_PORT_1}:54663
      - ${BAMBOO_PORT_2}:8085

  atl-bitbucket-db:
    image: postgres:12-alpine
    container_name: atl-bitbucket-db
    restart: unless-stopped
    env_file: env/postgres-bitbucket.env
    volumes:
      - ${POSTGRES_VOLUME_DATA_BITBUCKET}:/var/lib/postgresql/data
    networks:
      - db
  
  atl-bamboo-db:
    image: postgres:12-alpine
    container_name: atl-bamboo-db
    restart: unless-stopped
    env_file: env/postgres-bamboo.env
    volumes:
      - ${POSTGRES_VOLUME_DATA_BAMBOO}:/var/lib/postgresql/data
    networks:
      - db

networks: 
  db:
    internal: true
